"""Development-only: dump Python's east-asian-width (W/F) and combining ranges, so the JS
Canvas measures cells exactly like the Python player (unicodedata.east_asian_width/combining)."""
import json, sys, unicodedata
def ranges(pred):
    out=[]; start=None
    for cp in range(0x110000):
        hit=pred(chr(cp))
        if hit and start is None: start=cp
        if not hit and start is not None: out.append([start, cp-1]); start=None
    return out
wide=ranges(lambda ch: unicodedata.east_asian_width(ch) in ('W','F'))
comb=ranges(lambda ch: unicodedata.combining(ch)!=0)
open(sys.argv[1],'w').write('// GENERATED by tools/gen-width.py (Unicode %s) — do not edit.\nexport const WIDE = %s\nexport const COMBINING = %s\n' % (unicodedata.unidata_version, json.dumps(wide,separators=(',',':')), json.dumps(comb,separators=(',',':'))))
